name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"
          working-directory: ./ok-foods

      - name: Change Directory and Install Dependencies
        working-directory: ./ok-foods # Change the working directory
        run: |
          npm install

      - name: Generate Environment File
        working-directory: ./ok-foods # Change the working directory
        run: |
          node generate-env.js
        env:
          NODE_ENV: production
          foodSpecialsSas: ${{ secrets.FOOD_SPECIALS_SAS }}
          foodSpecialsUrl: ${{ secrets.FOOD_SPECIALS_URL }}
          liquorSpecialsSas: ${{ secrets.LIQUOR_SPECIALS_SAS }}
          liquorSpecialsUrl: ${{ secrets.LIQUOR_SPECIALS_URL }}
          generalSas: ${{ secrets.GENERAL_SAS }}
          generalUrl: ${{ secrets.GENERAL_URL }}
          ownerName: ${{ secrets.OWNER_NAME }}
          managerName: ${{ secrets.MANAGER_NAME }}
          foodImageName: ${{ secrets.FOOD_IMAGE_NAME }}
          liquorImageName: ${{ secrets.LIQUOR_IMAGE_NAME }}
          contactImageName: ${{ secrets.CONTACT_IMAGE_NAME }}
          logoName: ${{ secrets.LOGO_NAME }}

      - name: Build Application
        working-directory: ./ok-foods
        run: |
          npm run build

      - name: List Build Output
        run: |
          cd ok-foods/dist/ok-foods/browser
          ls -la

      - name: Build And Deploy

        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          working-directory: ./ok-foods
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_AGREEABLE_SAND_0AC26D003 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          app_location: "./ok-foods" # App source code path
          output_location: "dist/ok-foods/browser"

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_AGREEABLE_SAND_0AC26D003 }}
          action: "close"
